// Public viewer for a shared Financial Review. No auth, no workspace
// context - anyone with the link sees a read-only copy. NOT under the
// `(app)` group, so it inherits only the root layout (no sidebar).
//
// Ungated: a share can be created by free users. Access is controlled
// purely by possession of the unguessable token.

import type { Metadata } from "next";
import Link from "next/link";
import Logo from "@/components/Logo";
import { prisma } from "@/lib/db";
import { FinancialReviewResultSchema } from "@/lib/financialReview/types";
import ReviewDetail from "../../../(app)/financial-review/ReviewDetail";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Shared private financials should never be indexed.
export const metadata: Metadata = {
  robots: { index: false, follow: false },
  title: "Shared Financial Review",
};

export default async function SharedReviewPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;

  const review = await prisma.financialReview.findUnique({
    where: { shareToken: token },
    select: {
      reportType: true,
      fileName: true,
      status: true,
      statusLevel: true,
      result: true,
      createdAt: true,
      business: { select: { name: true } },
    },
  });

  if (!review) {
    return (
      <ShareShell>
        <NotFound />
      </ShareShell>
    );
  }

  const parsed =
    review.status === "complete" && review.result
      ? FinancialReviewResultSchema.safeParse(review.result)
      : null;

  return (
    <ShareShell workspaceName={review.business?.name ?? null} title={review.reportType || review.fileName}>
      {parsed?.success ? (
        <ReviewDetail result={parsed.data} level={review.statusLevel} />
      ) : (
        <div className="mx-auto max-w-xl card text-center">
          <div className="t-section text-slate-100 mb-2">This review isn&apos;t available</div>
          <div className="t-body text-slate-400">
            The shared review may still be processing or could not be loaded. Ask the sender to re-share it.
          </div>
        </div>
      )}
    </ShareShell>
  );
}

function ShareShell({
  workspaceName,
  title,
  children,
}: {
  workspaceName?: string | null;
  title?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen flex flex-col bg-brand-navy">
      <header className="border-b border-line bg-ink-900/40">
        <div className="container-wide flex items-center justify-between gap-4 py-4 flex-wrap">
          <Link href="/" aria-label="Tweaxly home" className="inline-block">
            <Logo size="sm" />
          </Link>
          <div className="min-w-0 text-right">
            {workspaceName ? (
              <div className="t-section truncate max-w-[60vw] leading-tight tracking-tight text-slate-100">
                {workspaceName}
              </div>
            ) : null}
            <div className="t-meta mt-1 font-semibold uppercase tracking-[0.22em] text-slate-400">
              Shared Financial Review
            </div>
          </div>
        </div>
      </header>

      <main className="flex-1 container-wide py-10 md:py-14">
        {title ? <h1 className="t-page mb-6">{title}</h1> : null}
        {children}
      </main>

      <footer className="border-t border-line bg-ink-900/40">
        <div className="container-wide flex items-center justify-between gap-4 py-6 flex-wrap">
          <div className="t-meta text-slate-500">Generated by Tweaxly AI Business Intelligence</div>
          <a href="https://app.tweaxly.com/register" className="btn-primary px-4 py-2 text-sm">
            Start Free
          </a>
        </div>
      </footer>
    </div>
  );
}

function NotFound() {
  return (
    <div className="mx-auto max-w-xl card text-center">
      <div className="t-section text-slate-100 mb-2">This shared review could not be found</div>
      <div className="t-body text-slate-400">
        The link may be incorrect or the share may have been turned off by its creator. Double-check the URL with the sender.
      </div>
    </div>
  );
}
