import { Lead, H2, ArticleLink, DefinitionBlock, Formula, KeyTakeaways } from "@/components/article";
import type { ArticleModule } from "./types";

export const meta: ArticleModule["meta"] = {
  slug: "roi",
  title: "ROI",
  excerpt:
    "ROI: Return on Investment. The profit generated by an investment relative to its cost. The standard way to compare different uses of capital.",
  category: "business-glossary",
  tags: ["ROI", "Return on Investment", "Investment Analysis"],
  author: { name: "Tweaxly Team", role: "Learning Center" },
  publishedAt: "2026-05-29",
  readingTime: 2,
  kind: "glossary",
  difficulty: "beginner",
  tldr: [
    "Stands for: Return on Investment.",
    "Formula: ROI = (Profit from investment ÷ Cost of investment) × 100%.",
    "Tells you: How efficiently capital is being used.",
    "Most useful for: Comparing alternative uses of capital, evaluating completed investments.",
    "Don't confuse with: ROAS (Return on Ad Spend - revenue rather than profit).",
  ],
  faq: [
    { q: "What does ROI stand for?", a: "Return on Investment. A measure of how much profit (or return) an investment generated relative to its cost." },
    { q: "How is ROI calculated?", a: "ROI = (Profit from investment ÷ Cost of investment) × 100%. A $10K investment that generated $3K of profit has 30% ROI." },
    { q: "What's a good ROI?", a: "Depends on context. Marketing campaigns: 3-5x (300-500% ROI) is healthy. Capital equipment: 20-30% annual ROI is good. Compare to alternative uses of the same capital." },
    { q: "What's the difference between ROI and ROAS?", a: "ROI uses profit; ROAS uses revenue. ROAS is easier to calculate (no need to factor in cost of goods or margins) but less honest about actual return." },
    { q: "How does ROI handle the time dimension?", a: "Basic ROI doesn't. Two investments with the same ROI but different payback periods aren't equivalent. Annualized ROI or IRR (Internal Rate of Return) handles time better." },
    { q: "Can ROI be negative?", a: "Yes - it means the investment lost money. A -20% ROI means you lost 20% of what you put in." },
  ],
  seo: {
    title: "ROI - Return on Investment Definition | Tweaxly",
    description: "ROI is Return on Investment. The profit from an investment relative to its cost. Plain-English definition with formula and examples.",
    keywords: ["ROI", "return on investment", "what is ROI", "ROI formula", "investment return"],
  },
};

export const Body = () => (
  <>
    <Lead>
      The standard yardstick for whether an investment was worth
      it. ROI lets you compare apples to oranges - a marketing
      campaign against a piece of equipment against a new hire -
      in the same units.
    </Lead>

    <DefinitionBlock term="ROI (Return on Investment)">
      the profit (or return) generated by an investment relative
      to its cost, expressed as a percentage. ROI =
      (Profit ÷ Investment Cost) × 100%.
    </DefinitionBlock>

    <Formula formula={"ROI = (Profit from investment ÷ Cost of investment) × 100%\n\nExample: $10,000 investment generated $3,000 profit. ROI = ($3,000 ÷ $10,000) × 100% = 30%."} />

    <H2 id="common-use">Common uses</H2>
    <ul>
      <li><strong>Investment comparison</strong> - which use of capital produces more return?</li>
      <li><strong>Post-investment evaluation</strong> - did this campaign or purchase pay back?</li>
      <li><strong>Resource allocation</strong> - directing budget toward higher-ROI activities</li>
    </ul>

    <H2 id="watch-out">Watch out</H2>
    <p>
      Basic ROI ignores time. A 50% ROI over five years isn&apos;t the same as a 50% ROI over six months. Use annualized ROI or IRR when time matters.
    </p>

    <H2 id="related">Related terms</H2>
    <ul>
      <li><ArticleLink href="/resources/business-glossary/roas">ROAS (Return on Ad Spend)</ArticleLink></li>
      <li><ArticleLink href="/resources/business-glossary/customer-payback-period">Customer Payback Period</ArticleLink></li>
      <li><ArticleLink href="/resources/business-glossary/ltv">LTV (Customer Lifetime Value)</ArticleLink></li>
      <li><ArticleLink href="/resources/business-glossary/cac">CAC (Customer Acquisition Cost)</ArticleLink></li>
      <li><ArticleLink href="/resources/business-glossary/profitability-ratio">Profitability Ratio</ArticleLink></li>
    </ul>

    <KeyTakeaways items={[
      "ROI = (Profit ÷ Investment Cost) × 100%.",
      "Standard way to compare investments in the same units.",
      "Doesn't handle time - use annualized ROI or IRR when timing matters.",
      "Can be negative (you lost money).",
    ]} />
  </>
);
