import {
  Lead, H2, H3, Callout, ArticleLink,
  DefinitionBlock, Formula, KeyTakeaways,
} from "@/components/article";
import type { ArticleModule } from "./types";

export const meta: ArticleModule["meta"] = {
  slug: "what-is-cash-flow",
  title: "What Is Cash Flow? A Plain-English Guide",
  excerpt:
    "Cash flow is the actual money moving in and out of your business. Different from profit, more important for survival - here's how it works.",
  category: "cash-flow-management",
  tags: ["Cash Flow", "Financial Basics", "Liquidity"],
  author: { name: "Tweaxly Team", role: "Learning Center" },
  publishedAt: "2026-05-29",
  readingTime: 7,
  tldr: [
    "Cash flow is the actual money moving in and out of your business over a period - cash in minus cash out.",
    "Three categories: operating cash flow (from the core business), investing cash flow (equipment, assets), and financing cash flow (debt, equity).",
    "Free cash flow = operating cash flow − capital expenditures. The cash actually available for owners, growth, or savings.",
    "Cash flow is not the same as profit. A profitable business can have negative cash flow; a loss-making business can have positive cash flow.",
    "Most cash flow problems are timing problems - the money is real but hasn't arrived (or has already left) at the right moment.",
  ],
  faq: [
    { q: "What's the simplest definition of cash flow?", a: "The actual money that moves through your bank account over a period. Cash in (from customers, loans, investors) minus cash out (to vendors, payroll, lenders, equipment). What's left is your cash flow." },
    { q: "Is cash flow the same as profit?", a: "No. Profit is what you earned on paper after every cost. Cash flow is what physically moved through your bank account. They can disagree significantly because of timing, non-cash expenses, and balance-sheet movements." },
    { q: "What's free cash flow?", a: "Operating cash flow (cash generated by the core business) minus capital expenditures (money spent on equipment and assets). It's the cash actually available for owners, growth, debt repayment, or savings." },
    { q: "What are the three types of cash flow?", a: "Operating cash flow (from running the business), investing cash flow (buying/selling assets), and financing cash flow (loans, equity, distributions). Operating is the most important; the other two are episodic." },
    { q: "Why is cash flow more important than profit for survival?", a: "Because bills are paid in cash, not in profit. Payroll, rent, vendor invoices - all demand cash on the due date. A profitable business that runs out of cash can't pay them and stops operating." },
    { q: "How can I improve my cash flow without growing revenue?", a: "Three levers: collect faster (tighten payment terms, follow up on receivables), pay slower (negotiate longer terms with vendors), and hold less inventory. Each shortens the cash conversion cycle without touching the top line." },
  ],
  seo: {
    title: "What Is Cash Flow? A Plain-English Guide | Tweaxly",
    description:
      "Cash flow is the actual money in and out of your business. A plain-English guide to types of cash flow, formulas, and why it matters more than profit.",
    keywords: [
      "what is cash flow",
      "cash flow",
      "operating cash flow",
      "free cash flow",
      "cash flow vs profit",
    ],
  },
};

export const Body = () => (
  <>
    <Lead>
      Profit is what your business earned on paper. Cash flow is what
      it actually has in the bank. The difference is the most
      important distinction in small business finance, and the one
      most owners learn the expensive way.
    </Lead>

    <DefinitionBlock term="Cash flow">
      the actual money moving in and out of your business over a
      period of time. Cash in (collections, loans, investments)
      minus cash out (vendor payments, payroll, debt service,
      equipment). Lives on the cash flow statement and is visible
      directly on your bank statements.
    </DefinitionBlock>

    <H2 id="three-types">The three types of cash flow</H2>

    <p>
      A cash flow statement splits all cash movements into three
      buckets. Each tells you something different about how your
      business funds itself.
    </p>

    <H3>1. Operating cash flow</H3>

    <p>
      Cash generated (or consumed) by the core business: collections
      from customers, payments to vendors and employees, rent,
      utilities, taxes. This is the most important of the three
      because it&apos;s the engine - a business that can&apos;t
      generate positive operating cash flow over the long run
      can&apos;t survive.
    </p>

    <H3>2. Investing cash flow</H3>

    <p>
      Cash used to buy (or generated by selling) long-term assets:
      equipment, vehicles, buildings, software, acquisitions. Most
      growing businesses have negative investing cash flow because
      they&apos;re buying things to grow.
    </p>

    <H3>3. Financing cash flow</H3>

    <p>
      Cash from external sources: loans taken out or paid back,
      investor money, owner contributions, dividends or distributions
      paid out. This is how the business funds itself when operating
      cash flow isn&apos;t enough (or returns capital when it is).
    </p>

    <Formula
      formula={"Total cash flow = Operating CF + Investing CF + Financing CF\n\nFree cash flow = Operating CF − Capital expenditure (the cash spent on equipment/assets)"}
      example={
        <>
          A small wholesaler has +$60K operating cash flow, −$25K
          investing cash flow (bought delivery equipment), and +$10K
          financing cash flow (drew on a credit line). Total cash
          flow = <strong>+$45K</strong>. Free cash flow ={" "}
          <strong>$60K − $25K = $35K</strong>.
        </>
      }
    />

    <H2 id="cash-flow-vs-profit">Cash flow vs profit: the most important distinction</H2>

    <p>
      Three reasons cash flow and profit disagree:
    </p>

    <ul>
      <li>
        <strong>Timing.</strong> Profit recognizes revenue when
        earned (invoice sent); cash flow recognizes it when collected
        (payment received). Same with expenses.
      </li>
      <li>
        <strong>Non-cash expenses.</strong> Depreciation lowers
        profit but doesn&apos;t move cash. The cash for the equipment
        left when it was bought; depreciation just spreads that
        historical cost over future periods.
      </li>
      <li>
        <strong>Balance-sheet movements.</strong> Buying inventory,
        paying down loan principal, distributing to owners - all use
        cash without touching profit.
      </li>
    </ul>

    <p>
      The deep dive is in our{" "}
      <ArticleLink href="/resources/financial-fundamentals/cash-flow-vs-profit">
        Cash Flow vs Profit
      </ArticleLink>{" "}
      article. The implication: a business can be profitable and
      cash-poor at the same time, especially during growth - the
      pattern explained in{" "}
      <ArticleLink href="/resources/cash-flow-management/why-profitable-businesses-run-out-of-cash">
        Why Profitable Businesses Run Out of Cash
      </ArticleLink>.
    </p>

    <Callout variant="info" title="The cash conversion cycle">
      The gap between paying out cash (for inventory, payroll,
      production) and collecting it back from customers is called
      the cash conversion cycle. Shorter cycles need less working
      capital; longer cycles tie up more cash. Most operational
      cash flow improvements come from shortening this cycle.
    </Callout>

    <H2 id="why-it-matters">Why cash flow matters more than profit (in the short term)</H2>

    <p>
      Bills get paid in cash, not in profit. Payroll, rent, vendor
      invoices, taxes - every one of them demands actual money on
      the due date. A profitable business that can&apos;t pay these
      stops operating, no matter what the P&L says.
    </p>

    <p>
      The hierarchy that matters in practice:
    </p>

    <ol>
      <li>
        <strong>Cash this week.</strong> Can you pay the bills due
        in the next 7 days?
      </li>
      <li>
        <strong>Cash this quarter.</strong> Will you have enough to
        cover the next 90 days, accounting for expected receipts and
        outflows?
      </li>
      <li>
        <strong>Profit this year.</strong> Is the business making
        money over the long term?
      </li>
    </ol>

    <p>
      Profit is necessary for long-term survival. Cash is necessary
      for short-term survival. Watch both, but understand the order.
    </p>

    <H2 id="improving-cash-flow">Three levers to improve cash flow without growing revenue</H2>

    <H3>1. Collect faster</H3>

    <p>
      Tighter payment terms (net-30 instead of net-60), better
      receivables follow-up, deposits or partial payments upfront,
      automatic billing, prompt invoicing. Each shortens the gap
      between work done and cash collected.
    </p>

    <H3>2. Pay slower</H3>

    <p>
      Negotiate longer terms with vendors (net-45 or net-60),
      stagger non-critical purchases, use credit cards for
      operational expenses (you get up to 60 days of float). The
      goal is more cash in your hands, longer.
    </p>

    <H3>3. Hold less inventory</H3>

    <p>
      Inventory is cash sitting in a warehouse. Reducing safety
      stock, improving forecasting accuracy, and using
      just-in-time fulfillment all free up cash without affecting
      profit (much).
    </p>

    <p>
      Each of these levers is covered in more depth in{" "}
      <ArticleLink href="/resources/cash-flow-management/how-to-improve-cash-flow">
        How to Improve Cash Flow
      </ArticleLink>.
    </p>

    <H2 id="common-mistakes">Common mistakes with cash flow</H2>

    <H3>1. Treating profit as cash</H3>

    <p>
      The most expensive mistake. Reinvesting or distributing based
      on the P&L without checking the bank account leads to
      avoidable cash crunches.
    </p>

    <H3>2. Watching only month-end cash, not the trajectory</H3>

    <p>
      A snapshot of cash on the last day of the month tells you
      where you are. A rolling forecast tells you where you&apos;re
      heading. Both matter; the forecast catches problems earlier.
    </p>

    <H3>3. Conflating cash flow with revenue growth</H3>

    <p>
      Fast revenue growth often means worse cash flow, not better,
      because every new dollar of sales requires working capital
      before the cash arrives. Plan for it.
    </p>

    <H2 id="related">Related concepts</H2>

    <ul>
      <li>
        <ArticleLink href="/resources/financial-fundamentals/cash-flow-vs-profit">
          Cash Flow vs Profit
        </ArticleLink>{" "}
        - the deeper dive on why they disagree.
      </li>
      <li>
        <ArticleLink href="/resources/cash-flow-management/cash-flow-forecasting">
          Cash Flow Forecasting
        </ArticleLink>{" "}
        - how to project cash flow forward.
      </li>
      <li>
        <ArticleLink href="/resources/cash-flow-management/why-profitable-businesses-run-out-of-cash">
          Why Profitable Businesses Run Out of Cash
        </ArticleLink>{" "}
        - the classic failure mode.
      </li>
      <li>
        <ArticleLink href="/resources/cash-flow-management/how-to-improve-cash-flow">
          How to Improve Cash Flow
        </ArticleLink>{" "}
        - practical levers in depth.
      </li>
      <li>
        <ArticleLink href="/resources/cash-flow-management/how-much-cash-reserve">
          How Much Cash Reserve Should a Business Have
        </ArticleLink>{" "}
        - the safety buffer question.
      </li>
    </ul>

    <KeyTakeaways items={[
      "Cash flow = actual money in and out of your business over a period.",
      "Three types: operating (core business), investing (assets), financing (debt/equity).",
      "Free cash flow = operating cash flow − capital expenditure. The cash actually available.",
      "Cash flow is not profit. Both are real; they measure different things.",
      "Cash matters more than profit short-term: bills get paid in cash, not in profit.",
      "Three levers to improve cash flow without growing revenue: collect faster, pay slower, hold less inventory.",
    ]} />
  </>
);
