// Public viewer for a SharedAnalysis. No auth, no workspace context -
// the recipient just opens the link and sees a snapshot of the analysis
// as it existed at share-time. This route is intentionally NOT under
// the `(app)` group, so it inherits only the root layout (no sidebar,
// no app navigation, no workspace switcher).
//
// Decision flow:
//   1. Token unknown               -> NotFoundScreen
//   2. Expired                     -> ExpiredScreen
//   3. Disabled (manually revoked) -> ExpiredScreen (same copy on purpose)
//   4. Password-protected          -> PasswordGate (client component)
//   5. Open                        -> server-renders the snapshot directly
//      and increments the view counters in the same transaction
//
// `force-dynamic` keeps every request live - we never want a cached
// HTML response leaking the snapshot of share A to a visitor on link B
// (Next.js's per-route caching would be opportunistic otherwise).

import Link from "next/link";
import Logo from "@/components/Logo";
import { prisma } from "@/lib/db";
import SharedAnalysisRenderer from "./SharedAnalysisRenderer";
import PasswordGate from "./PasswordGate";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export default async function SharePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;

  const row = await prisma.sharedAnalysis.findUnique({
    where: { token },
    select: {
      id:              true,
      sourceType:      true,
      snapshotContent: true,
      snapshotMeta:    true,
      passwordHash:    true,
      expiresAt:       true,
      isActive:        true,
      createdAt:       true,
      firstViewedAt:   true,
    },
  });

  if (!row) {
    return <ShareShell><NotFoundScreen /></ShareShell>;
  }
  const expired  = row.expiresAt.getTime() < Date.now();
  const disabled = !row.isActive;
  if (expired || disabled) {
    return (
      <ShareShell>
        <ExpiredScreen expiresAt={row.expiresAt.toISOString()} />
      </ShareShell>
    );
  }

  if (row.passwordHash) {
    return (
      <ShareShell>
        <PasswordGate
          token={token}
          sourceType={row.sourceType}
          createdAt={row.createdAt.toISOString()}
          expiresAt={row.expiresAt.toISOString()}
        />
      </ShareShell>
    );
  }

  // No password, not expired, not disabled - render directly and
  // count this visit. Atomic counter update so concurrent visitors
  // don't lose increments to a lost-update race.
  const now = new Date();
  await prisma.sharedAnalysis.update({
    where: { id: row.id },
    data: {
      viewCount:     { increment: 1 },
      lastViewedAt:  now,
      firstViewedAt: row.firstViewedAt ?? now,
    },
  });

  return (
    <ShareShell>
      <SharedAnalysisRenderer
        sourceType={row.sourceType}
        snapshotContent={row.snapshotContent as Record<string, unknown>}
        snapshotMeta={row.snapshotMeta as Record<string, unknown>}
        createdAt={row.createdAt.toISOString()}
        expiresAt={row.expiresAt.toISOString()}
      />
    </ShareShell>
  );
}

// Page-level chrome reused across every state (not-found, expired,
// locked, rendered). Keeps the header / footer identical so the
// recipient always sees the same brand bar regardless of which
// state they hit.
function ShareShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex flex-col bg-brand-navy">
      <header className="border-b border-line bg-ink-900/40">
        <div className="container-wide flex items-center justify-between py-4 gap-4 flex-wrap">
          <Link href="/" aria-label="Tweaxly home" className="inline-block">
            <Logo size="sm" />
          </Link>
          <div className="t-meta uppercase tracking-[0.22em] text-slate-400 font-semibold">
            Shared Business Analysis
          </div>
        </div>
      </header>

      <main className="flex-1 container-wide py-10 md:py-14">
        {children}
      </main>

      <footer className="border-t border-line bg-ink-900/40">
        <div className="container-wide py-6 flex items-center justify-between gap-4 flex-wrap">
          <div className="t-meta text-slate-500">
            Generated by Tweaxly AI Business Intelligence
          </div>
          {/* Soft CTA - the recipient saw value in the shared analysis;
              this is the lowest-friction way to convert them into a
              free trial without competing with the analysis itself. */}
          <a
            href="https://app.tweaxly.com/register"
            className="btn-primary text-sm px-4 py-2"
          >
            Start Free
          </a>
        </div>
      </footer>
    </div>
  );
}

function NotFoundScreen() {
  return (
    <div className="max-w-xl mx-auto card text-center">
      <div className="t-section text-slate-100 mb-2">
        This shared analysis could not be found
      </div>
      <div className="t-body text-slate-400">
        The link may be incorrect or the share may have been deleted by its
        creator. Double-check the URL with the sender.
      </div>
    </div>
  );
}

function ExpiredScreen({ expiresAt }: { expiresAt: string }) {
  return (
    <div className="max-w-xl mx-auto card text-center">
      <div className="t-section text-slate-100 mb-2">
        This shared analysis has expired
      </div>
      <div className="t-body text-slate-400">
        The link expired on{" "}
        <span className="text-slate-300 font-medium">
          {new Date(expiresAt).toLocaleString()}
        </span>
        . Ask the sender to generate a new one if you still need access.
      </div>
    </div>
  );
}
